In [1]:
import pickle
import numpy as np
import pandas as pd
import tensorflow as tf

from tensorflow.python.platform import tf_logging as logging

C:\Users\vfgtr554\anaconda3\envs\cctv\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\vfgtr554\anaconda3\envs\cctv\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\vfgtr554\anaconda3\envs\cctv\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\vfgtr554\anaconda3\envs\cctv\lib\site-packages\tensorflow\

In [2]:
def calculate_laplacian(adj, lambda_max = 1):
    adj = normalized_adj

In [3]:
def __init__(self, num_units, adj, inputs, output_dim, activation=tf.nn.tanh,
            input_size = None, num_proj = None, reuse = None, **kwargs):
    super(GCN, self).__init__(**kwargs)
    
    self.num_unitus = num_units
    self.output_dim = output_dim
    self.inputs = inputs
    self.num_nodes = inputs.get_shape()[2].value
    self.input_dim = inputs.get_shape()[1].value
    self.batch_size = tf.shape(inputs)[0]
    
    self.adj = []
    self.adj.append(calculate_laplacian(adj))
    self.activation = activation
    self.gconv()

In [4]:
data_path = '../Data/METR-LA/speed_la.csv'
adj_path = '../Data/METR-LA/adj_mx_la.pkl'

In [5]:
with open(adj_path, 'rb') as file:
    data = pickle.load(file, encoding='latin1')
data

[['773869',
  '767541',
  '767542',
  '717447',
  '717446',
  '717445',
  '773062',
  '767620',
  '737529',
  '717816',
  '765604',
  '767471',
  '716339',
  '773906',
  '765273',
  '716331',
  '771667',
  '716337',
  '769953',
  '769402',
  '769403',
  '769819',
  '769405',
  '716941',
  '717578',
  '716960',
  '717804',
  '767572',
  '767573',
  '773012',
  '773013',
  '764424',
  '769388',
  '716328',
  '717819',
  '769941',
  '760987',
  '718204',
  '718045',
  '769418',
  '768066',
  '772140',
  '773927',
  '760024',
  '774012',
  '774011',
  '767609',
  '769359',
  '760650',
  '716956',
  '769831',
  '761604',
  '717495',
  '716554',
  '773953',
  '767470',
  '716955',
  '764949',
  '773954',
  '767366',
  '769444',
  '773939',
  '774067',
  '769443',
  '767750',
  '767751',
  '767610',
  '773880',
  '764766',
  '717497',
  '717490',
  '717491',
  '717492',
  '717493',
  '765176',
  '717498',
  '717499',
  '765171',
  '718064',
  '718066',
  '765164',
  '769431',
  '769430',
  '7

In [6]:
adj = data[2]
adj.shape

(207, 207)

In [7]:
adj

array([[1.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 1.       , 0.3909554, ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.7174379, 1.       , ..., 0.       , 0.       ,
        0.       ],
       ...,
       [0.       , 0.       , 0.       , ..., 1.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 1.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        1.       ]], dtype=float32)

In [8]:
data = pd.read_csv(data_path)
data = data.drop(['Unnamed: 0'], axis=1)
data

773869     767541     767542     717447     717446     717445  \
0      64.375000  67.625000  67.125000  61.500000  66.875000  68.750000   
1      62.666667  68.555556  65.444444  62.444444  64.444444  68.111111   
2      64.000000  63.750000  60.000000  59.000000  66.500000  66.250000   
3      64.000000  63.750000  60.000000  59.000000  66.500000  66.250000   
4      64.000000  63.750000  60.000000  59.000000  66.500000  66.250000   
...          ...        ...        ...        ...        ...        ...   
34267  65.000000  65.888889  68.555556  61.666667  32.833333  54.555556   
34268  61.375000  65.625000  66.500000  62.750000  32.833333  50.500000   
34269  67.000000  59.666667  69.555556  61.000000  32.833333  44.777778   
34270  66.750000  62.250000  66.000000  59.625000  32.833333  53.000000   
34271  65.111111  66.888889  66.777778  61.222222  32.833333  49.555556   

          773062     767620     737529     717816  ...     772167     769372  \
0      65.125000  67.125000  59.625000  62.750000  ...  45.625000  65.500000   
1      65.000000  65.000000  57.444444  63.333333  ...  50.666667  69.875000   
2      64.500000  64.250000  63.875000  65.375000  ...  44.125000  69.000000   
3      64.500000  64.250000  63.875000  65.375000  ...  44.125000  69.000000   
4      64.500000  64.250000  63.875000  65.375000  ...  44.125000  69.000000   
...          ...        ...        ...        ...  ...        ...        ...   
34267  62.444444  63.333333  59.222222  65.333333  ...  52.888889  69.000000   
34268  62.000000  67.000000  65.250000  67.125000  ...  54.000000  69.250000   
34269  64.222222  63.777778  59.777778  57.666667  ...  51.333333  67.888889   
34270  64.285714  64.125000  60.875000  66.250000  ...  51.125000  69.375000   
34271  65.777778  65.111111  63.000000  61.666667  ...  56.000000  67.444444   

          774204     769806     717590     717592     717595     772168  \
0      64.500000  66.428571  66.875000  59.375000  69.000000  59.250000   
1      66.666667  58.555556  62.000000  61.111111  64.444444  55.888889   
2      56.500000  59.250000  68.125000  62.500000  65.625000  61.375000   
3      56.500000  59.250000  68.125000  62.500000  65.625000  61.375000   
4      56.500000  59.250000  68.125000  62.500000  65.625000  61.375000   
...          ...        ...        ...        ...        ...        ...   
34267  65.111111  55.666667  66.333333  62.444444  66.777778  64.888889   
34268  60.125000  60.500000  67.250000  59.375000  66.000000  61.250000   
34269  64.333333  57.000000  66.000000  62.666667  68.666667  63.333333   
34270  61.625000  60.500000  65.625000  66.375000  69.500000  63.000000   
34271  64.888889  60.888889  64.222222  66.444444  68.444444  63.555556   

          718141     769373  
0      69.000000  61.875000  
1      68.444444  62.875000  
2      69.857143  62.000000  
3      69.857143  62.000000  
4      69.857143  62.000000  
...          ...        ...  
34267  69.666667  62.333333  
34268  69.000000  62.000000  
34269  67.444444  61.222222  
34270  67.875000  63.500000  
34271  68.666667  61.777778  

[34272 rows x 207 columns]

In [9]:
adj = np.mat(adj)

In [10]:
import scipy.sparse as sp

In [11]:
adj

matrix([[1.       , 0.       , 0.       , ..., 0.       , 0.       ,
         0.       ],
        [0.       , 1.       , 0.3909554, ..., 0.       , 0.       ,
         0.       ],
        [0.       , 0.7174379, 1.       , ..., 0.       , 0.       ,
         0.       ],
        ...,
        [0.       , 0.       , 0.       , ..., 1.       , 0.       ,
         0.       ],
        [0.       , 0.       , 0.       , ..., 0.       , 1.       ,
         0.       ],
        [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
         1.       ]], dtype=float32)

In [12]:
adj = sp.coo_matrix(adj + sp.eye(adj.shape[0]))
rowsum = np.array(adj.sum(1))
d_inv_sqrt = np.power(rowsum, -0.5).flatten()
d_inv_sqrt[np.isinf(d_inv_sqrt)] = 0.
d_mat_inv_sqrt = sp.diags(d_inv_sqrt)
normalized_adj = adj.dot(d_mat_inv_sqrt).transpose().dot(d_mat_inv_sqrt).tocoo()
normalized_adj = normalized_adj.astype(np.float32)
normalized_adj

<207x207 sparse matrix of type '<class 'numpy.float32'>'
	with 1722 stored elements in COOrdinate format>

In [13]:
adj = sp.csr_matrix(adj)
adj = adj.astype(np.float32)
adj

<207x207 sparse matrix of type '<class 'numpy.float32'>'
	with 1722 stored elements in Compressed Sparse Row format>

In [14]:
adj = adj.tocoo()
coords = np.vstack((adj.row, adj.col)).transpose()
coords

array([[  0,   0],
       [  0,  13],
       [  0,  37],
       ...,
       [206, 187],
       [206, 198],
       [206, 206]], dtype=int32)

In [15]:
L = tf.SparseTensor(coords, adj.data, adj.shape)
tf.sparse_reorder(L)

In [17]:
L

In [18]:
dir(L)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '_dense_shape',
 '_indices',
 '_override_operator',
 '_tf_api_names',
 '_tf_api_names_v1',
 '_values',
 'consumers',
 'dense_shape',
 'dtype',
 'eval',
 'from_value',
 'get_shape',
 'graph',
 'indices',
 'op',
 'shape',
 'values']

In [20]:
L._values

<tf.Tensor 'SparseTensor/values:0' shape=(1722,) dtype=float32>

In [21]:
T

NameError: name 'T' is not defined

In [22]:
TLQKFFUSDL


NameError: name 'TLQKFFUSDL' is not defined

In [23]:
asdp[katopkfopkasopdkopaskfopakdopaskd
    ][p]

NameError: name 'asdp' is not defined

In [24]:
Lspa dlkspd[f
           o SP{F}]

SyntaxError: invalid syntax (4021962491.py, line 1)

In [25]:
as][sadd []
   as[d
     [
         as{ }
     ]]]

SyntaxError: invalid syntax (1630455370.py, line 1)

In [26]:
AS{ d
  as[ d
    A{D 
     s[ad
       [as
       { }]]}]}

SyntaxError: invalid syntax (257595061.py, line 1)

In [27]:
[d 
as[ 
as [d
   as [
       sa[d
         as[d 
           as[d]]]
   ]]]]

SyntaxError: invalid syntax (3473700265.py, line 2)

In [28]:
AS{
    A{D}
}

SyntaxError: invalid syntax (3602416160.py, line 1)

In [29]:
A{D}

SyntaxError: invalid syntax (1711249932.py, line 1)

In [30]:
AS{D}

SyntaxError: invalid syntax (2404329100.py, line 1)

In [31]:
AS{D}

SyntaxError: invalid syntax (2404329100.py, line 1)

In [32]:
AS{DA}

SyntaxError: invalid syntax (2665485733.py, line 1)

In [33]:
S{D}

SyntaxError: invalid syntax (310253483.py, line 1)

In [34]:
AS{D}

SyntaxError: invalid syntax (2404329100.py, line 1)

In [35]:
AS{D}

SyntaxError: invalid syntax (2404329100.py, line 1)

In [36]:
AS{D}

SyntaxError: invalid syntax (2404329100.py, line 1)

In [37]:
AS{D}

SyntaxError: invalid syntax (2404329100.py, line 1)

In [38]:
SA{D}

SyntaxError: invalid syntax (1364653402.py, line 1)

In [ ]:
SA{
    
}