In [2]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.pyplot import style
style.use('seaborn-whitegrid')

device = "cuda" if torch.cuda.is_available() else "cpu"

In [19]:
class MultiRBFnn(nn.Module):
    def __init__(self, in_feature, add_rbf_num, device):
        super(MultiRBFnn, self).__init__()

        self.add_rbf_num = add_rbf_num  # additional RBFs number
        self.in_feature = in_feature    # count features
        self.device = device
        self.centers_list = []
        self.sigmas_list = []
        self.weights_list = []

        self.change_th = 3

    def first_rbf_parameter(self, input_data, target): # done

        # input_data shape : (data_num)
        # target data shape : (in_feature, data_num)
        
        # first layer centers, weights, sigmas
        # centers, sigmas : (add_rbf_num, 1)
        # weights : (in_feature, add_rbf_num)

        find_index_input = input_data.clone().detach()
        fine_index_target = target.clone().detach()

        find_sigma = target.clone().detach()
        find_weight = target.clone().detach()
        center_index_list = []

        # first MultiRBFs initial centers and weights parameters
        for i in range(self.add_rbf_num):
            index_ = torch.argmax(torch.sum(torch.abs(fine_index_target), dim = 0)).cpu().detach().tolist()
            fine_index_target[:,index_] = 0
            center_index_list.append(index_)

        center_index_list = torch.tensor(center_index_list, device= self.device)
        initcenter = torch.index_select(find_index_input, 0, center_index_list)[-self.add_rbf_num:].reshape(self.add_rbf_num,1)
        initweight = torch.index_select(find_weight, 1, center_index_list)[-self.add_rbf_num:].reshape(self.in_feature, self.add_rbf_num)

        # first MultiRBFs initial sigmas parameters                
        sigma_list = []
        dft = torch.log(torch.abs(torch.fft.fft(find_sigma).real))
        dft =  torch.abs(dft / torch.max(dft)) **-1
        for k in center_index_list:
            sigma_list.append(torch.mean(dft[:,k]).reshape(1))

        initsigma = torch.cat(sigma_list)[-self.add_rbf_num:].reshape(self.add_rbf_num, 1)

        # print(initcenter, initweight, initsigma)
        return initcenter, initweight, initsigma
    
    def add_rbf_parameter(self, input_data, error):
        find_index_input = input_data.clone().detach()
        find_index_error = error.clone().detach()
        
        find_weight = error.clone().detach()
        find_sigma = error.clone().detach()
        
        center_index_list = []

        for i in range(self.add_rbf_num * (self.change_time + 1)):
            index_ = torch.argmax(torch.sum(torch.abs(find_index_error), dim = 0)).cpu().detach().tolist()

            find_index_error[:,index_] = 0
            center_index_list.append(index_)

        center_index_list = torch.tensor(center_index_list, device=self.device)
        initcenter = torch.index_select(find_index_input, 0, center_index_list)[-self.add_rbf_num:].reshape(self.add_rbf_num,1)
        initweight = torch.index_select(find_weight, 1, center_index_list)[::,-self.add_rbf_num:].reshape(self.in_feature, self.add_rbf_num)


        sigma_list = []
        dft = torch.log(torch.abs(torch.fft.fft(find_sigma).real))
        
        dft = (torch.abs(dft / torch.max(dft))**-1)
        for k in center_index_list:
            sigma_list.append(torch.mean(dft[:,k]).reshape(1))
        initsigma = torch.cat(sigma_list)[-self.add_rbf_num:].reshape(self.add_rbf_num,1)
        #print(initcenter, initweight, initsigma)
        return initcenter, initweight, initsigma
    
    
    def rbf_gaussian(self, input_data):
        out = torch.exp(-1 *(torch.pow((input_data - self.centers), 2)) / (torch.pow(self.sigma, 2)))

        return out

    def forward(self, input_data):
        R = self.rbf_gaussian(input_data)
        pred = torch.mm(self.weights, R)

        return R, pred

    def rbf_gaussian_derivative_centers(self, input_data): # done
        output = (2 * (input_data - self.centers) / (torch.pow(self.sigma, 2))) * self.rbf_gaussian(input_data)

        return output  # size = (add_rbf_num, data_num)

    def rbf_gaussian_derivative_sigma(self, input_data): # done
        output = (2 * torch.pow((input_data - self.centers), 2) / (torch.pow(self.sigma, 3))) * self.rbf_gaussian(input_data)

        return output  # size = (add_rbf_num, data_num)
    
    # FUNCTION GRADIENT
    def rbf_gradient(self, input_data, centers, sigmas, weights):
        rbf_output = (-2 * (input_data-centers) / torch.pow(sigmas,2)) * \
                        (torch.exp(-1 * (torch.pow((input_data - centers), 2) / (torch.pow(sigmas, 2)))))
        rbf_grad = torch.mm(weights, rbf_output)
        
        return rbf_grad
    
    def first_grad(input_data, target):
        space = (input_data,)
        for i in range(target.size(0)):
            if i == 0:
                f_grad = torch.gradient(target[i], spacing = space, edge_order  = 1)[0]
            else:
                f_grad = torch.vstack([f_grad, torch.gradient(target[i], spacing = space, edge_order  = 1)[0]])
        return f_grad
    
    def target_grad(self, input_data, centers, sigmas, weights, f_grad):
        true_grad = f_grad - self.rbf_gradient(input_data, centers, sigmas, weights)
        
        return true_grad
    
    def rbf_gaussian_derivative_centers(self, input_data):
        output = (2 * (input_data - self.centers) / \
                  (torch.pow(self.sigma, 2))) * self.rbf_gaussian(input_data)

        return output  # size = (num_radial, 1)
    
    def rbf_gaussian_derivative_sigma(self, input_data):
        output = (2 * torch.pow((input_data - self.centers), 2) / \
                (torch.pow(self.sigma, 3))) * self.rbf_gaussian(input_data)

        return output  # size = (num_radial, 1)

    def L2_F(self, input_data):
        return -2 * (input_data - self.centers) / torch.pow(self.sigma, 2)
    
    def L2_2_derivateive_weight(self, input_data, radial_output):
        return (-2 *(input_data - self.centers) / torch.pow(self.sigma,2)) * radial_output
    
    def masking(self, target):
    
        # value_masking vector
        value_masking = torch.where(target.isnan(), 0.0, 1.0)

        # gradient masking vector
        dim1 = (target.isnan().nonzero(as_tuple=True)[0]).detach().cpu().to().tolist()
        dim2_backward = (target.isnan().nonzero(as_tuple=True)[1] + 1).detach().cpu().to().tolist()
        dim2_forward = (target.isnan().nonzero(as_tuple=True)[1] -1).detach().cpu().to().tolist()

        grad_masking = torch.where(target.isnan(), 0.0, 1.0)
        grad_masking[dim1, dim2_backward] = 0.0
        grad_masking[dim1, dim2_forward] = 0.0
        
        return value_masking, grad_masking


    # Backpropagation and train

    def BP(self, input_data, target, R, pred, target_grad, pred_grad):
        L2_1_error = -2 * (target - pred)

        L2_2_error = -2 * (target_grad - pred_grad)

        observation_len = torch.sum(self.value_missng)

        # sigma update
        deltaSigma1 = self.rbf_gaussian_derivative_sigma(input_data) * L2_1_error.reshape(self.in_feature, 1, input_data.size(0))
        deltaSigma1 *= self.weights.reshape(self.in_feature, self.add_rbf_num, 1)

        deltaSigma2 = self.rbf_gaussian_derivative_sigma(input_data) * L2_2_error.reshape(self.in_feature, 1, input_data.size(0))
        deltaSigma2 *= self.L2_F(input_data) * self.weights.reshape(self.in_feature, self.add_rbf_num, 1)

        # deltaSigma =  torch.mean(torch.sum(deltaSigma1, dim=2), dim = 0) + torch.mean(torch.sum(deltaSigma2, dim=2), dim = 0)
        deltaSigma = torch.sum(deltaSigma1, dim=2) / observation_len + torch.sum(deltaSigma2, dim=2) / observation_len

        # center update
        deltaCenter1 = self.rbf_gaussian_derivative_centers(input_data) * L2_1_error.reshape(self.in_feature, 1, input_data.size(0))
        deltaCenter1 *= self.weights.reshape(self.in_feature, self.add_rbf_num, 1)

        deltaCenter2 = self.rbf_gaussian_derivative_centers(input_data) * L2_2_error.reshape(self.in_feature, 1, input_data.size(0))
        deltaCenter2 *= self.L2_F(input_data) * self.weights.reshape(self.in_feature, self.add_rbf_num, 1)
        # deltaCenter =  torch.mean(torch.sum(deltaCenter1, dim=2), dim = 0) + torch.mean(torch.sum(deltaCenter2, dim=2), dim = 0)
        deltaCenter =  torch.sum(deltaCenter1, dim=2) / observation_len + torch.sum(deltaCenter2, dim=2) / observation_len
        
        # weight update
        delta_weight1 = torch.sum((R * L2_1_error.reshape(self.in_feature, 1, input_data.size(0))), dim=2)
        delta_weight2 = torch.sum(self.L2_2_derivateive_weight(input_, R) * L2_2_error.reshape(self.in_feature, 1, input_data.size(0)), dim = 2)
        delta_weight = delta_weight1 + delta_weight2
        
        # BP update
        self.weights -= self.lr * delta_weight
        #self.centers -= self.lr * torch.sum(deltaCenter1, dim=1).reshape(self.add_rbf_num, 1)
        #self.sigma -= self.lr * torch.sum(deltaSigma1, dim=1).reshape(self.add_rbf_num, 1)
        self.centers -= self.lr * deltaCenter.reshape(self.add_rbf_num, 1)
        self.sigma -= self.lr * deltaSigma.reshape(self.add_rbf_num, 1)

    def change_init(self, na):
        if na == 1:
            loss_list = self.train_loss_list[-self.change_th:]
            if self.number > self.change_th and max(loss_list) == min(loss_list):
                self.change_time += 1
            elif self.number > self.change_th and loss_list[0] < loss_list[1] and loss_list[1] < loss_list[2]:
                self.change_time += 1
            else:
                self.change_time = 0
        else:
            self.change_time += 1
    
    def plot_train(self, input_data, best_pred): #done
        if self.in_feature != 1:
            fig, ax = plt.subplots(1, self.in_feature, figsize = (30, 5))
            for i in range(self.in_feature):
                ax[i].plot(input_data.cpu().detach().numpy(), self.target[i].cpu().detach().numpy())
                ax[i].plot(input_data.cpu().detach().numpy(), best_pred[i].cpu().detach().numpy())
            plt.show()
        
        else:
            plt.plot(input_data.cpu().detach().numpy(), self.target[0].cpu().detach().numpy())
            plt.plot(input_data.cpu().detach().numpy(), best_pred[0].cpu().detach().numpy())
            plt.show()

    def best_forward(self, input_data, best_center, best_sigma, best_weight): # ?
        rbf_output = torch.exp(-1 * (torch.pow((input_data - best_center), 2) / \
                                        (torch.pow(best_sigma, 2))))
        pred = torch.mm(best_weight, rbf_output)

        return pred
    
    def Loss(self, pred, target, pred_grad, true_grad):
        # value L2 loss  

        return torch.sum(torch.pow(target - pred,2) + torch.pow(true_grad - pred_grad, 2)) / torch.sum(self.value_masking)
    
    def pred(self, input_data):
        rbf_output = torch.exp(-1 * (torch.pow((input_data - self.done_centers), 2) / \
                                     (torch.pow(self.done_sigma, 2))))
        pred = torch.mm(self.done_weights, rbf_output)

        return rbf_output, pred
        
    def train(self, input_data, target, epochs, lr, loss_th, lr_change_th):
        self.lr = lr
        self.target = target.clone().detach()
        self.number = 0
        self.train_loss_list = []
        self.loss_th = loss_th
        self.lr_change_th = lr_change_th
        self.target_mape_th = torch.mean(torch.abs(target)) * 0.05
        self.round_number = 5
        self.change_time = 0
        count_loss_chage = 0
        count_round_change = 0

        break_time = len(input_data) / self.add_rbf_num

        loss = 100000
        
        while self.loss_th < loss:

            print("{}th additional rbflayer".format(self.number))
            # first rbflayer
            if self.number == 0:
                self.value_masking, self.grad_masking = self.masking(self.target)
                self.centers, self.weights, self.sigma = self.first_rbf_parameter(input_data, self.target)
                first_grad = torch.nan_to_num(self.first_grad(input_data, target))

                for epoch in range(epochs):
                    # print("epoch : {}".format(epoch))
                    R, pred = self.forward(input_data)
                    rbf_grad = self.rbf_gradient(input_data, self.centers, self.sigma, self.weights) * self.value_masking

                    self.BP(input_data, self.target, R, pred, first_grad, rbf_grad)
                    R, pred = self.forward(input_data)
                    rbf_grad = self.rbf_gradient(input_data, self.centers, self.sigma, self.weights) * self.value_masking
                    epoch_loss = self.Loss(pred, self.target, rbf_grad, first_grad)

                    if epoch == 0:
                        print("{}th additional RBFlayer {}th epoch loss: {}".format(self.number, epoch, epoch_loss))
                        self.best_loss = epoch_loss.clone().detach()
                        self.best_center = self.centers.clone().detach()
                        self.best_sigma = self.sigma.clone().detach()
                        self.best_weight = self.weights.clone().detach()
                    
                    else:
                        if self.best_loss > epoch_loss:
                            self.best_loss = epoch_loss.clone().detach()
                            self.best_center = self.centers.clone().detach()
                            self.best_sigma = self.sigma.clone().detach()
                            self.best_weight = self.weights.clone().detach()

                    if (epoch + 1) % 1000 == 0:
                        print("{}th additional RBFlayer {}th epoch MSE Loss: {}".format(self.number, epoch, epoch_loss))

            else:
                self.change_init(na)
                if self.change_time > break_time:
                    break
                
                
                self.centers, self.weights, self.sigma = self.add_rbf_parameter(input_data, self.target)

                for epoch in range(epochs):
                    # print('epoch : {}'.format(epoch))
                    R, pred = self.forward(input_data)
                    rbf_grad = self.rbf_gradient(input_data, self.centers, self.sigma, self.weights) * self.value_masking
                    if epoch == 0:
                        
                        print("{}th additional RBFlayer {}th epoch loss: {}".format(self.number, epoch,
                                                                                        self.Loss(pred, self.target, rbf_grad, torch.nan_to_num(target_grad))))
                        self.best_loss = self.Loss(pred, self.target, rbf_grad, torch.nan_to_num((target_grad).clone().detach()))
                        self.best_center = self.centers.clone().detach()
                        self.best_sigma = self.sigma.clone().detach()
                        self.best_weight = self.weights.clone().detach()

                    self.BP(input_data, self.target, R, pred, torch.nan_to_num(target_grad), rbf_grad)
                    # R, pred = self.forward(input_data)
                    # rbf_grad = self.rbf_gradient(input_data, self.centers, self.sigma, self.weights)
                    epoch_loss = self.Loss(pred, self.target, rbf_grad, torch.nan_to_num(target_grad))

                    if (epoch + 1) % 1000 == 0:
                        print("{}th additional RBFlayer {}th epoch MSE Loss: {}".format(self.number, epoch, epoch_loss))
                    
                    if self.best_loss > epoch_loss:
                        self.best_loss = epoch_loss.clone().detach()
                        self.best_center = self.centers.clone().detach()
                        self.best_sigma = self.sigma.clone().detach()
                        self.best_weight = self.weights.clone().detach()
                
            best_pred = self.best_forward(input_data, self.best_center, self.best_sigma, self.best_weight)
            best_grad = self.rbf_gradient(input_data, self.best_center, self.best_sigma, self.best_weight)
            if self.number ==0:
                train_loss = self.Loss(best_pred, self.target, best_grad, first_grad)
            else:
                train_loss = self.Loss(best_pred, self.target, best_grad, target_grad)

            print("{}th additional RBFlayer best loss : {}".format(self.number, train_loss))

            if self.best_loss < self.lr_change_th:
                count_loss_chage += 1
                self.lr *= 10
                self.lr_change_th *= 0.03
                print("change lr ", self.lr)
                print('----------------------------------------------')
                
            if count_round_change == 0 and train_loss < self.target_mape_th:
                count_round_change += 1
                self.round_number += 1
                print("change round number", self.round_number)
                print('----------------------------------------------')
                
            self.train_loss_list.append(train_loss)

            # additional rbf plot print
            self.plot_train(input_data, best_pred)

            if torch.isnan(train_loss) == False:
                na = 1
                self.target = self.target - best_pred  # target update
                loss = train_loss  # loss update
                self.number += 1  # additional rbf number update
                self.centers_list.append(self.best_center)
                self.sigmas_list.append(self.best_sigma)
                self.weights_list.append(self.best_weight)

                self.done_centers = torch.cat(self.centers_list, dim  =0)
                self.done_sigma = torch.cat(self.sigmas_list, dim = 0)
                self.done_weights = torch.cat(self.weights_list, dim = 1)
                target_grad = self.target_grad(input_data, self.done_centers, self.done_sigma, self.done_weights, first_grad)

            else:
                na = 0
    

In [4]:
def gaussian(input_data, centers, sigma, weights):
    out = torch.exp(-1 *(torch.pow((input_data - centers), 2)) / (torch.pow(sigma, 2)))
    pred = torch.mm(weights, out)
    return pred

In [5]:
r_c = torch.tensor([1.32141, 6.1256142, 4.21512, 3.16512, 7.1626, 8.735, 12.1624], dtype = float ,device= device).reshape(7,1)
r_s = torch.tensor([1.1, 0.6142, 2.21512, 1.162, 0.626, 2.735, 1.1624], dtype = float ,device= device).reshape(7,1)
r_w = torch.tensor([[-10, 12, 32, -33, 12, -20, 3],
                    [12, -1, -22, 3, 32, -20, 4],
                    [-10, 3, 23, -13, 23, 17, 2]], dtype = float, device = device)

input_ = np.arange(1,15,0.5)
input_ = torch.tensor(input_, device = device)
target = gaussian(input_, r_c, r_s, r_w)
target2 = gaussian(input_, r_c, r_s, r_w)

target[0][2] = torch.nan
target[0][6] = torch.nan
target[0][9] = torch.nan
target[0][15] = torch.nan
target[0][16] = torch.nan

target[1][3] = torch.nan
target[1][5] = torch.nan
target[1][1] = torch.nan
target[1][19] = torch.nan
target[1][26] = torch.nan

In [8]:
def first_grad(input_data, target):
        space = (input_data,)
        for i in range(target.size(0)):
            if i == 0:
                f_grad = torch.gradient(target[i], spacing = space, edge_order  = 1)[0]
            else:
                f_grad = torch.vstack([f_grad, torch.gradient(target[i], spacing = space, edge_order  = 1)[0]])
        return f_grad

In [9]:
f_grad = first_grad(input_, target)

In [10]:
f_grad

tensor([[-1.0956e+00,         nan,         nan,         nan,  7.2457e+00,
                 nan,         nan,         nan,         nan,         nan,
                 nan, -1.5153e+01, -1.6674e+01, -2.0885e+01,         nan,
                 nan,         nan,         nan,  5.5819e+00,  7.0520e+00,
          7.7610e+00,  7.0996e+00,  4.7793e+00,  1.8948e+00,  8.5873e-02,
         -2.7246e-01, -1.9558e-02,  1.2505e-01],
        [        nan,         nan,         nan,         nan,         nan,
                 nan,         nan, -1.3192e+00,  1.7292e+00,  3.5034e+00,
          1.2825e+01,  3.0663e+01,  1.3275e+01, -2.6326e+01, -2.5216e+01,
         -5.5639e+00,  1.4930e+00,  3.9654e+00,         nan,         nan,
                 nan,  7.7167e+00,  4.9768e+00,  1.5093e+00, -5.6717e-01,
                 nan,         nan,         nan],
        [ 1.0192e+00,  3.6913e+00,  6.4545e+00,  6.6090e+00,  8.8155e+00,
          1.2330e+01,  1.1697e+01,  6.1017e+00,  7.8346e-01, -1.0606e-01,
          4.74

In [11]:
f_grad2 = first_grad(input_, target2)
f_grad2

tensor([[-1.0956e+00, -8.6308e-01, -2.6247e+00, -2.6924e+00,  7.2457e+00,
          2.0858e+01,  2.3095e+01,  1.1836e+01,  7.5424e-01, -1.6531e+00,
         -8.6341e+00, -1.5153e+01, -1.6674e+01, -2.0885e+01, -1.5262e+01,
         -4.6339e+00,  5.9779e-01,  3.4890e+00,  5.5819e+00,  7.0520e+00,
          7.7610e+00,  7.0996e+00,  4.7793e+00,  1.8948e+00,  8.5873e-02,
         -2.7246e-01, -1.9558e-02,  1.2505e-01],
        [-2.5422e+00, -7.2688e+00, -1.3379e+01, -1.3580e+01, -1.1116e+01,
         -8.5495e+00, -5.3172e+00, -1.3192e+00,  1.7292e+00,  3.5034e+00,
          1.2825e+01,  3.0663e+01,  1.3275e+01, -2.6326e+01, -2.5216e+01,
         -5.5639e+00,  1.4930e+00,  3.9654e+00,  5.8708e+00,  7.4428e+00,
          8.3705e+00,  7.7167e+00,  4.9768e+00,  1.5093e+00, -5.6717e-01,
         -7.8528e-01, -2.6806e-01, -4.2164e-03],
        [ 1.0192e+00,  3.6913e+00,  6.4545e+00,  6.6090e+00,  8.8155e+00,
          1.2330e+01,  1.1697e+01,  6.1017e+00,  7.8346e-01, -1.0606e-01,
          4.74

In [35]:
target[target != target.isnan(), target != target.isnan()] 

IndexError: too many indices for tensor of dimension 2

In [48]:
target[target.isnan() == False]

tensor([-6.3209e+00, -6.8688e+00, -9.4935e+00, -9.8764e+00, -2.2478e+00,
         2.0847e+01,  2.2817e+01,  2.1164e+01,  1.2967e+01,  6.0111e+00,
        -3.7070e+00, -1.4874e+01, -1.8371e+01, -1.6019e+01, -1.2789e+01,
        -8.9670e+00, -5.0283e+00, -1.8674e+00, -2.4894e-01,  2.7321e-02,
        -1.6306e-01, -2.4514e-01, -1.8262e-01,  8.4284e+00,  1.1596e+00,
        -1.2420e+01, -2.0970e+01, -2.2654e+01, -2.2289e+01, -2.0925e+01,
        -1.8786e+01, -8.1002e+00,  1.1878e+01,  5.1751e+00, -1.4448e+01,
        -2.0041e+01, -2.0012e+01, -1.8548e+01, -1.6047e+01, -8.6037e+00,
        -4.3066e+00, -8.8700e-01,  6.7013e-01,  6.2229e-01,  1.0296e-01,
        -1.6510e-01, -6.7820e+00, -6.2724e+00, -3.0908e+00,  1.8207e-01,
         3.5182e+00,  8.9976e+00,  1.5848e+01,  2.0695e+01,  2.1950e+01,
         2.1478e+01,  2.1844e+01,  2.6222e+01,  3.7997e+01,  3.3637e+01,
         2.0899e+01,  1.7660e+01,  1.7063e+01,  1.5809e+01,  1.3814e+01,
         1.1475e+01,  9.3000e+00,  7.5634e+00,  6.0

In [12]:
def masking(target):
    
    # value_masking vector
    value_masking = torch.where(target.isnan(), 0.0, 1.0)

    # gradient masking vector
    dim1 = (target.isnan().nonzero(as_tuple=True)[0]).detach().cpu().to().tolist()
    dim2_backward = (target.isnan().nonzero(as_tuple=True)[1] + 1).detach().cpu().to().tolist()
    dim2_forward = (target.isnan().nonzero(as_tuple=True)[1] -1).detach().cpu().to().tolist()

    grad_masking = torch.where(target.isnan(), 0.0, 1.0)
    grad_masking[dim1, dim2_backward] = 0.0
    grad_masking[dim1, dim2_forward] = 0.0
    
    return value_masking, grad_masking
    

In [25]:
torch.sum(Vm, dim = 1).reshape(3,1)

tensor([[23.],
        [23.],
        [28.]], device='cuda:0')

In [13]:
Vm,Gm = masking(target)

In [18]:
torch.nan_to_num(Vm * f_grad)

tensor([[-1.0956e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  7.2457e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00, -1.5153e+01, -1.6674e+01, -2.0885e+01,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  5.5819e+00,  7.0520e+00,
          7.7610e+00,  7.0996e+00,  4.7793e+00,  1.8948e+00,  8.5873e-02,
         -2.7246e-01, -1.9558e-02,  1.2505e-01],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00, -1.3192e+00,  1.7292e+00,  3.5034e+00,
          1.2825e+01,  3.0663e+01,  1.3275e+01, -2.6326e+01, -2.5216e+01,
         -5.5639e+00,  1.4930e+00,  3.9654e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  7.7167e+00,  4.9768e+00,  1.5093e+00, -5.6717e-01,
          0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 1.0192e+00,  3.6913e+00,  6.4545e+00,  6.6090e+00,  8.8155e+00,
          1.2330e+01,  1.1697e+01,  6.1017e+00,  7.8346e-01, -1.0606e-01,
          4.74

In [65]:
def first_grad(input_data, target):
    space = (input_data,)
    f_grad = torch.gradient(target, spacing = space, edge_order  = 1)
    return f_grad[0]

In [66]:
target

tensor([[-6.3209e+00, -6.8688e+00,         nan, -9.4935e+00, -9.8764e+00,
         -2.2478e+00,         nan,  2.0847e+01,  2.2817e+01,         nan,
          2.1164e+01,  1.2967e+01,  6.0111e+00, -3.7070e+00, -1.4874e+01,
                 nan,         nan, -1.8371e+01, -1.6019e+01, -1.2789e+01,
         -8.9670e+00, -5.0283e+00, -1.8674e+00, -2.4894e-01,  2.7321e-02,
         -1.6306e-01, -2.4514e-01, -1.8262e-01],
        [ 8.4284e+00,         nan,  1.1596e+00,         nan, -1.2420e+01,
                 nan, -2.0970e+01, -2.2654e+01, -2.2289e+01, -2.0925e+01,
         -1.8786e+01, -8.1002e+00,  1.1878e+01,  5.1751e+00, -1.4448e+01,
         -2.0041e+01, -2.0012e+01, -1.8548e+01, -1.6047e+01,         nan,
         -8.6037e+00, -4.3066e+00, -8.8700e-01,  6.7013e-01,  6.2229e-01,
          1.0296e-01,         nan, -1.6510e-01],
        [-6.7820e+00, -6.2724e+00, -3.0908e+00,  1.8207e-01,  3.5182e+00,
          8.9976e+00,  1.5848e+01,  2.0695e+01,  2.1950e+01,  2.1478e+01,
          2.18

In [14]:
Vm, Gm = masking(target)

In [15]:
def rbf_gradient(input_data, centers, sigmas, weights):
    rbf_output = (-2 * (input_data-centers) / torch.pow(sigmas,2)) * \
                    (torch.exp(-1 * (torch.pow((input_data - centers), 2) / (torch.pow(sigmas, 2)))))
    rbf_grad = torch.mm(weights, rbf_output)
    
    return rbf_grad

In [16]:
rbf_Grad = rbf_gradient(input_, r_c, r_s, r_w)

In [17]:
rbf_Grad * Gm

tensor([[-3.0780e+00,  0.0000e+00, -0.0000e+00, -0.0000e+00,  6.1463e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00, -0.0000e+00, -0.0000e+00,
         -0.0000e+00, -1.9561e+01, -1.1700e+01, -2.6177e+01, -0.0000e+00,
         -0.0000e+00,  0.0000e+00,  0.0000e+00,  5.6809e+00,  7.1520e+00,
          7.9918e+00,  7.4446e+00,  4.9054e+00,  1.6483e+00, -2.0872e-01,
         -3.5560e-01,  2.1655e-02,  1.8062e-01],
        [ 0.0000e+00, -0.0000e+00, -0.0000e+00, -0.0000e+00, -0.0000e+00,
         -0.0000e+00, -0.0000e+00, -1.1543e+00,  2.2340e+00,  2.8364e+00,
          8.3427e+00,  3.7602e+01,  2.4370e+01, -4.3282e+01, -2.4671e+01,
         -2.6106e+00,  1.7646e+00,  4.0255e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  8.1564e+00,  5.1419e+00,  1.1892e+00, -9.4635e-01,
         -0.0000e+00, -0.0000e+00,  0.0000e+00],
        [-2.4946e+00,  4.4576e+00,  7.1676e+00,  5.9368e+00,  8.3396e+00,
          1.3298e+01,  1.2784e+01,  6.0279e+00, -3.1569e-01, -4.8709e-01,
          2.22

In [30]:
coordinates = (torch.tensor([-2., -1.,0, 1.,2, 4.]),)
values = torch.tensor([4., 1., 0, 1.,4., 16.], )
torch.gradient(values, spacing = coordinates)

(tensor([-3., -2.,  0.,  2.,  4.,  6.]),)

In [31]:
coordinates = (torch.tensor([-2., -1., 2., 4.]),)
values = torch.tensor([4., 1., 4., 16.], )
torch.gradient(values, spacing = coordinates)

(tensor([-3.0000, -2.0000,  4.0000,  6.0000]),)

In [26]:
target

tensor([[-6.3209e+00, -6.8688e+00,         nan, -9.4935e+00, -9.8764e+00,
         -2.2478e+00,         nan,  2.0847e+01,  2.2817e+01,         nan,
          2.1164e+01,  1.2967e+01,  6.0111e+00, -3.7070e+00, -1.4874e+01,
                 nan,         nan, -1.8371e+01, -1.6019e+01, -1.2789e+01,
         -8.9670e+00, -5.0283e+00, -1.8674e+00, -2.4894e-01,  2.7321e-02,
         -1.6306e-01, -2.4514e-01, -1.8262e-01],
        [ 8.4284e+00,         nan,  1.1596e+00,         nan, -1.2420e+01,
                 nan, -2.0970e+01, -2.2654e+01, -2.2289e+01, -2.0925e+01,
         -1.8786e+01, -8.1002e+00,  1.1878e+01,  5.1751e+00, -1.4448e+01,
         -2.0041e+01, -2.0012e+01, -1.8548e+01, -1.6047e+01,         nan,
         -8.6037e+00, -4.3066e+00, -8.8700e-01,  6.7013e-01,  6.2229e-01,
          1.0296e-01,         nan, -1.6510e-01],
        [-6.7820e+00, -6.2724e+00, -3.0908e+00,  1.8207e-01,  3.5182e+00,
          8.9976e+00,  1.5848e+01,  2.0695e+01,  2.1950e+01,  2.1478e+01,
          2.18

In [ ]:
def rbf_gaussian_derivative_centers(self, input_data):
    output = (2 * (input_data - self.centers) / \
                (torch.pow(self.sigma, 2))) * self.rbf_gaussian(input_data)

    return output  # size = (num_radial, 1)

In [39]:
Dc = torch.tensor([[1],[3],[4],[5]], device = device, dtype=float)

In [34]:
weights = torch.tensor([[-10,4, 12,5],
                        [12,3, -1,5],
                        [-10,5, 3,5]], dtype = float, device = device)

In [40]:
deltaCenter2 = Dc * torch.nan_to_num(target).reshape(3, 1, input_.size(0))

In [44]:
torch.mean(torch.sum(deltaCenter2 * weights.reshape(3, 4, 1), dim = 2).size())

torch.Size([3, 4])

In [ ]:
deltaCenter2 = rbf_gaussian_derivative_centers(input_) * torch.nan_to_num(target).reshape(3, 1, input_.size(0))
deltaCenter2 *= L2_F(input_) * weights.reshape(3, add_rbf_num, 1)

In [47]:
def first_rbf_parameter( input_data, target): # done

    # input_data shape : (data_num)
    # target data shape : (3, data_num)
    
    # first layer centers, weights, sigmas
    # centers, sigmas : (4, 1)
    # weights : (3, 4)

    find_index_input = input_data.clone().detach()
    fine_index_target = target.clone().detach()

    find_sigma = target.clone().detach()
    find_weight = target.clone().detach()
    center_index_list = []

    # first MultiRBFs initial centers and weights parameters
    for i in range(4):
        index_ = torch.argmax(torch.sum(torch.abs(fine_index_target), dim = 0)).cpu().detach().tolist()
        fine_index_target[:,index_] = 0
        center_index_list.append(index_)

    center_index_list = torch.tensor(center_index_list, device= device)
    initcenter = torch.index_select(find_index_input, 0, center_index_list)[-4:].reshape(4,1)
    initweight = torch.index_select(find_weight, 1, center_index_list)[-4:].reshape(3, 4)

    # first MultiRBFs initial sigmas parameters                
    sigma_list = []
    dft = torch.log(torch.abs(torch.fft.fft(find_sigma).real))
    dft =  torch.abs(dft / torch.max(dft)) **-1
    for k in center_index_list:
        sigma_list.append(torch.mean(dft[:,k]).reshape(1))

    initsigma = torch.cat(sigma_list)[-4:].reshape(4, 1)

    # print(initcenter, initweight, initsigma)
    return initcenter, initweight, initsigma

In [49]:
first_rbf_parameter(input_, torch.nan_to_num(target))

(tensor([[5.0000],
         [4.5000],
         [6.0000],
         [7.0000]], device='cuda:0', dtype=torch.float64),
 tensor([[ 22.8171,  20.8468,  21.1640,   6.0111],
         [-22.2889, -22.6541, -18.7855,  11.8778],
         [ 21.9499,  20.6950,  21.8439,  37.9970]], device='cuda:0',
        dtype=torch.float64),
 tensor([[2.0927],
         [2.1295],
         [2.1708],
         [3.0031]], device='cuda:0', dtype=torch.float64))

In [50]:
first_rbf_parameter(input_, torch.nan_to_num(target2))

(tensor([[5.0000],
         [4.5000],
         [5.5000],
         [6.0000]], device='cuda:0', dtype=torch.float64),
 tensor([[ 22.8171,  20.8468,  21.6011,  21.1640],
         [-22.2889, -22.6541, -20.9249, -18.7855],
         [ 21.9499,  20.6950,  21.4785,  21.8439]], device='cuda:0',
        dtype=torch.float64),
 tensor([[3.1214],
         [2.3658],
         [5.0884],
         [3.1916]], device='cuda:0', dtype=torch.float64))